# Generated by Django 2.1.4 on 2018-12-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
