# Generated by Django 2.1.4 on 2018-12-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
